import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {QueryClient, QueryClientProvider, useQuery} from '@tanstack/react-query';
import './style.css';

const sections=['Dashboard','Rerank Playground','Batch Playground','Models','Runtime','Cache','Benchmarks','Requests','System Health','Settings','Audit Log'];
const path:Record<string,string>={Dashboard:'dashboard',Models:'models',Runtime:'runtime',Cache:'cache',Benchmarks:'benchmarks',Requests:'requests','System Health':'system/health',Settings:'runtime','Audit Log':'audit-log'};
async function api(url:string,token:string,options:RequestInit={}){const r=await fetch('/v1/'+url,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...options.headers}});if(!r.ok)throw new Error((await r.json()).error?.message||r.statusText);return r.json()}
export function Login({onLogin}:{onLogin:(t:string)=>void}){const [token,setToken]=useState('');return <main className="login"><form onSubmit={e=>{e.preventDefault();onLogin(token)}}><h1>Reranker Console</h1><p>Operational control plane</p><label>Admin token<input aria-label="Admin token" type="password" value={token} onChange={e=>setToken(e.target.value)} autoFocus/></label><button>Sign in</button></form></main>}
function Playground({token,batch=false}:{token:string,batch?:boolean}){const [query,setQuery]=useState("Describe the candidate's Kubernetes experience");const [docs,setDocs]=useState('Basic conceptual knowledge of Kubernetes. No hands-on production experience.\nProduction experience with Docker and Docker Compose.');const [result,setResult]=useState<any>();const run=async()=>{const request={query,documents:docs.split('\n').filter(Boolean).map((text,i)=>({id:`doc-${i+1}`,text})),top_n:10,return_documents:true,truncate:true};setResult(await api(batch?'rerank/batch':'rerank',token,{method:'POST',body:JSON.stringify(batch?{requests:[request]}:request)}))};return <section><h2>{batch?'Batch':'Rerank'} Playground</h2><label>Query<textarea value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Documents — one per line<textarea rows={8} value={docs} onChange={e=>setDocs(e.target.value)}/></label><button onClick={run}>Run rerank</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section>}
function DataView({section,token}:{section:string,token:string}){const endpoint='admin/'+path[section];const {data,error,isLoading,refetch}=useQuery({queryKey:[endpoint],queryFn:()=>api(endpoint,token),refetchInterval:section==='Dashboard'?10000:false});if(isLoading)return <div className="skeleton">Loading…</div>;if(error)return <div className="error">{String(error)}</div>;return <section><header><h2>{section}</h2><button className="secondary" onClick={()=>refetch()}>Refresh</button></header><pre>{JSON.stringify(data,null,2)}</pre></section>}
export function App(){const [token,setToken]=useState(()=>sessionStorage.getItem('adminToken')||'');const [section,setSection]=useState(location.hash.slice(1)||'Dashboard');const login=(t:string)=>{sessionStorage.setItem('adminToken',t);setToken(t)};useEffect(()=>{location.hash=section},[section]);if(!token)return <Login onLogin={login}/>;return <div className="shell"><aside><div className="brand">RR <span>Console</span></div>{sections.map(s=><button className={s===section?'active':''} onClick={()=>setSection(s)} key={s}>{s}</button>)}<button onClick={()=>{sessionStorage.clear();setToken('')}}>Log out</button></aside><main>{section==='Rerank Playground'?<Playground token={token}/>:section==='Batch Playground'?<Playground token={token} batch/>:<DataView section={section} token={token}/>}</main></div>}
const root = document.getElementById('root');
if (root) createRoot(root).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider></React.StrictMode>);
